name: terraform_github_action

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tagid:
        description: 'Tag ID'     
        required: true


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./azurerm_resource_group
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: infra-deploy
        run: |
          sudo apt-get -y update; sudo apt-get -y install git curl jq python3-pip; sudo apt-get -y install wget unzip
          sudo pip3 install -U awscli
          sudo curl -fsSL https://get.docker.com -o get-docker.sh         
          ls -la           
          rm -rf .terraform
          terraform init 
          terraform validate -no-color
          terraform plan 
          terraform destroy --auto-approve 